name: Remote Update and Deploy

on:
  push:
    branches:
      - master  # تشغيل الـ Workflow عند دفع التحديثات على فرع master

jobs:
  remote-update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment (stable Node 18)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'  # Use stable Node.js 18

      # Deploy on remote server
      - name: Deploy Application on Remote Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Navigate to the project directory
            cd /var/www/html/ve-shop.co/ve-frontend
            
            # Stash local changes and pull the latest changes
            git stash --include-untracked
            git pull origin master
            
            # Clean up any old files
            if [ -f package-lock.json ]; then
              rm package-lock.json
            fi
            
            # Ensure Yarn is installed
            if ! command -v yarn &> /dev/null; then
              npm install -g yarn
            fi
            
            # Remove node_modules and install fresh dependencies
            rm -rf node_modules
            yarn install  # Ensure dependencies are installed without --frozen-lockfile
            
            # Verify if next is installed
            if ! yarn list | grep next; then
              echo "Next.js is not installed, attempting to install..."
              yarn add next
            fi
            # Build the project
            yarn build
            
            # Run the application (بدون PM2)
            yarn start &  # تشغيل التطبيق في الخلفية
            
            # Restart Nginx to apply changes
            sudo systemctl restart nginx
          timeout: 60s  # Set timeout for SSH action
          command_timeout: 15m  # Allow enough time for dependencies installation and build process
          debug: true  # Enable detailed logs for debugging

      # Final confirmation message
      - name: Confirm Deployment Success
        run: echo "Deployment completed successfully on remote server."
