name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # تأكد من ضبط الإصدار المناسب

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Deploy to server
        run: |
          ssh username@your-vps-ip << 'EOF'
          cd /path/to/your/app
          git pull origin main
          yarn install --production
          yarn build
          pm2 restart all  # أو يمكنك تحديد اسم التطبيق لو كان موجوداً
          sudo systemctl restart nginx
          EOF
          
