name: Remote Update and Deploy

on:
  push:
    branches:
      - master  # تشغيل الـ Workflow عند دفع التحديثات على فرع master

jobs:
  remote-update-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.4'

    - name: Connect to Remote Server and Run Update Commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/html/ve-shop.co/ve-frontend
          
          # تحديث الكود من المستودع
          git stash
          git pull origin master

          # تثبيت Yarn و PM2 إذا لم يكونا مثبتين
          if ! command -v yarn &> /dev/null; then
            npm install -g yarn
          fi
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          # حذف التبعيات القديمة وتثبيت الجديدة
          rm -rf node_modules
          yarn install

          # بناء التطبيق
          yarn build

          # إدارة العملية باستخدام PM2
          if pm2 list | grep -q "ve-frontend"; then
            pm2 restart ve-frontend
          else
            pm2 start yarn --name "ve-frontend" -- start
          fi

          pm2 save  # حفظ العمليات في PM2 للبدء التلقائي
