name: Remote Update and Deploy

on:
  push:
    branches:
      - master

jobs:
  remote-update-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.4'

    - name: Connect to Remote Server and Run Update Commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/html/ve-shop.co/ve-frontend
          git stash --include-untracked
          git pull origin master
          [ -f package-lock.json ] && rm package-lock.json
          if ! command -v yarn &> /dev/null; then
            npm install -g yarn
          fi
          rm -rf node_modules
          yarn install  # Remove --frozen-lockfile
          yarn build
          if [ -d ".next" ]; then
            echo "Build successful!"
            yarn copy-build
          else
            echo "Build failed!"
            exit 1
          fi
