name: Remote Update and Deploy

on:
  push:
    branches:
      - master  # Triggers the workflow on pushes to the master branch

jobs:
  remote-update-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.13.0'

    - name: Connect to Remote Server and Run Update Commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/html/ve-shop.co/ve-frontend
          git stash
          git pull origin master
          if [ -f package-lock.json ]; then
            rm package-lock.json
          fi
          if ! command -v yarn &> /dev/null; then
            npm install -g yarn
          fi
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi
          rm -rf node_modules
          yarn install
          yarn build
          pm2 stop ve-frontend || true
          pm2 start yarn --name "ve-frontend" -- start
          pm2 startup  # Ensures PM2 restarts on reboot
          pm2 save
          pm2 restart ve-frontend
